---

- name: create directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: jenkins_admin
    group: jenkins_admin
    mode: 0775
  loop:
    - /opt/jenkins
    - /opt/jenkins/resources
    - /opt/jenkins/resources/init.groovy.d

- name: Install docker-compose.yaml
  template:
    src: docker-compose.yaml.j2
    dest: /opt/jenkins/docker-compose.yaml
    mode: 0644

- name: Install Dockerfile
  template:
    src: Dockerfile.j2
    dest: /opt/jenkins/Dockerfile
    mode: 0644

- name: Install Makefile
  template:
    src: Makefile.j2
    dest: /opt/jenkins/Makefile
    mode: 0644